Hubble 1990
  - Ben Moon, 14 Jun 1990
  - Malcolm Smith, 1992 
  - Jon Gaskins, 1994
  - Steve Dunning, 
  - Steve McClure Aug 2009
  - Alex Megos, 31 May 2016
  - Will Bosi, 25 Oct 2016
  - Pete Dawson Aug 2019
  - Mathew Wright Oct 2020
  - Buster Martin Oct 2020

Liquid Ambar 1990
  - Jerry Moffatt 1990
  - Ben Moon 1993?
  - Pete Robbins Aug 2009
  - Kieran Forrest Jul 2020

Sea of Tranquillity 1993
  - Ben Moon
  - Neil Carson ??
  - Pete Robbins Oct 2010
  - Pete Dawson, 15 Aug 2019 - 8c 

Progress
	"Due to the loss of some holds in 1997, Steve McClure upgraded the climb from 8c to 8c+ following his ascent in 2006." https://www.ukclimbing.com/news/2016/06/progress_8c+_for_jon_freeman-70535
  - Jerry Moffatt
  - Nic Sellars, 1995
  - Steve McClure, 2006
  - Chris Savage, 
  - Alex Megos, 2016 2nd go
  - Jon Freeman, 19 Jun 2016
  - Luke Dawson, 20 Jun 2020
  - Tim Palmer

Evolution 1995
- Jerry Moffatt, 13 May 1995
- Malcolm Smith
- Nic Sellars
- Ryan Pasquill, Sept 2009
- Alex Megos, 2016, 3rd try
- Luke Dawson, 15 Apr 2016
- Will Bosi, Jul 2017, 3rd try
- Stu Littlefair, 24 Oct 2018
- Pete Dawson, Nov 2018
- Ben Moon, Nov 2018
- Mat Wright, Sept 2019

Total Eclipse 1995?
  - John Dunne

The Bastard 1995
  - John Welford, 20 July 1995
  - Steve McClure, 


The Big Bang 1996
  - Neil Carson 1996
  - James McHaffie, Jul 2011
  - Emma Twyford, 2019
  - Kieran Forrest, Sept 2020



Mutation 1998
  - Steve McClure, Summer 1998


Northern Lights 2000 (year before Biographie)
  - Steve McClure, 2000
  - Adam Ondra, 2010
  - Alex Megos, 2017


Rainshadow 2003
  - Steve McClure 2003
  - Adam Ondra, 2011
  - Jordan Buys, May 2013
  - Ben Moon June 2015
  - Stu Littlefair 8 Sept 2015
  - Will Bosi 2016
  - Ryan Pasquill May 2018
  - Pete Dawson Jun 2018
  - Toby Roberts, Dec 2020
  - Josh Ibbertson, Dec 2020

Hajj 2004
  - Steve McClure, 2004

Violent New Breed 2004
  - John Gaskins, 21 Jun 2004

Overshadow 2007
  - Steve McClure 2007
  - Adam Ondra 2011

North Star 2008
  - Steve McClure, 20 May 2008
  - Adam Ondra, 2011

Stevolution 2008 or 2009
  - Steve McClure, 2009
  - Ryan Pasquill ??

Hunger 2010
  - Malcolm Smith, 2010
  - Dave Macleod,

Meltdown 2012
  - James McHaffie, Jul 2012 

King of Theives 2014
  - Jordan Buys, 15 Sep 2014
  - Luke Dawson, 12 Sep 2020

Brian
  - Ken Palmer
  - Pete Dawson, 2 July 2017
  - Luke Dawson, 29 Oct 2018

Sabotage 2016
  - Neil Gresham, Oct 2016
  - Jon Freeman, 22 Sep 2020


Fixation 2020
  - Steve McClure, September 2020
