Hubble
 grade: 9a
 year: 1990
 ascents:
  - Ben Moon
      ascent: first
      date: 14 Jun 1990
  - Malcolm Smith
      ascent: second
      date: 1992 
  - Jon Gaskins:
      ascent: third
      date: 1994
  - Steve Dunning
      ascent: fourth
      date: 
  - Steve McClure
      ascent: fifth
      date: Aug 2009
  - Alex Megos
      ascent: sixth
      date: 31 May 2016
  - Will Bosi
      ascent: seventh
      date: 25 Oct 2016
  - Pete Dawson
      ascent: eighth
      date: Aug 2019
  - Mathew Wright
      ascent: ninth
      date: Oct 2020
  - Buster Martin
       ascent: tenth
       date: Oct 2020

Liquid Ambar
  grade: 8c+
  year: 1990
  ascents:
  - Jerry Moffatt
      ascent: first
      date: 1990
  - Ben Moon
      ascent: second
      date: 1993
  - Pete Robbins
      ascent: third
      date: Aug 2009
  - Kieran Forrest
      ascent: fourth
      date: Jul 2020


Sea of Tranquillity
  grade: 8c/+
  year: 1993
  ascents:
  - Ben Moon
      ascent: first
      date: 1998
  - Neil Carson
      ascent: 
      date: 
  - Pete Robbins
      ascent: second
      date: Oct 2010
  - Pete Dawson
      ascent: third
      date: 15 Aug 2019
      notes: 8c 

Progress
  grade: 8c+
	info: "Due to the loss of some holds in 1997, Steve McClure upgraded the climb from 8c to 8c+ following his ascent in 2006." https://www.ukclimbing.com/news/2016/06/progress_8c+_for_jon_freeman-70535
  year:
  ascents:
  - Jerry Moffatt
      ascent: first
      date: 
  - Nic Sellars
      ascent: second
      date: 1995
  - Steve McClure
      ascent: third
      date: 2006
  - Chris Savage
      ascent: fourth
      date: 
  - Alex Megos
      ascent: fifth
      date: 2016
      notes: 2nd go
  - Jon Freeman
      ascent: sixth
      date: 19 Jun 2016
  - Luke Dawson
      ascent: seventh
      date: 20 Jun 2020
  - Tim Palmer
      ascent: eighth
      date: 

Evolution
  grade: 8c+
  year: 1995
  ascents:
  - Jerry Moffatt
      ascent: first
      date: 13 May 1995
  - Malcolm Smith
      ascent: second
      date:
  - Nic Sellars
      ascent: third
      date:
  - Ryan Pasquill
      ascent: fourth
      date: Sept 2009
  - Alex Megos
      ascent: fifth
      date: 2016
      notes: 3rd try
  - Luke Dawson
      ascent: sixth
      date: 15 Apr 2016
  - Will Bosi
     ascent: seventh
     date: Jul 2017
     notes: 3rd try
  - Stu Littlefair
      ascent: eighth
      date: 24 Oct 2018
  - Pete Dawson
      ascent: ninth
      date: Nov 2018
  - Ben Moon
      ascent: tenth
      date: Nov 2018
  - Mat Wright
      ascent: eleventh
      date: Sept 2019

Total Eclipse
  grade: 
  year: 1995
  ascents:
  - John Dunne
      ascent: first
      date: 1995

The Bastard
  grade: 8c+
  year: 1995
  note: originally graded 8c
  ascents:
  - John Welford
      ascent: first
      date: 20 July 1995
  - Steve McClure
      ascent: second
      date: 


The Big Bang
  grade: 9a
  year: 1996
  ascents:
  - Neil Carson
      ascent: first
      year: 1996
  - James McHaffie
      ascent: second
      date: Jul 2011
  - Emma Twyford
      ascent: third
      date: 2019
  - Kieran Forrest
      ascent: fourth
      date: Sept 2020

Mutation
  grade: 9a
  year: 1998
  ascents:
  - Steve McClure
      ascent: first
      date: Summer 1998


Northern Lights
  grade: 9a
  year: 2000
  ascents:
  - Steve McClure
      ascent: first
      date: 2000
  - Adam Ondra
      ascent: second
      date: 2010
  - Alex Megos
      ascent: third
      date: 2017

Rainshadow
  grade: 9a
  year: 2003
  ascents:
  - Steve McClure
      ascent: first
      date: 2003
  - Adam Ondra
      ascent: second
      date: 2011
  - Jordan Buys
      ascent: third
      date: May 2013
  - Ben Moon
      ascent: fourth
      date: June 2015
  - Stu Littlefair
      ascent: fifth
      date: 8 Sept 2015
  - Will Bosi
      ascent: sixth
      date: 2016
  - Ryan Pasquill
      ascent: seventh
      date: May 2018
  - Pete Dawson
      ascent: eighth
      date: Jun 2018
  - Toby Roberts
      ascent: ninth
      date: Dec 2020
  - Josh Ibbertson
      ascent: tenth
      date: Dec 2020

Hajj
  grade: 8c+
  year: 2004
  ascent: 
  - Steve McClure
      ascent: first
      date: 2004

Violent New Breed
  grade: 9a+
  year: 2004
  ascents:
    - John Gaskins
      date: 21 Jun 2004

Metalcore
  grade: 8c+
  year: 2007
  ascents:
  - Dave Macleod
      ascent: first
      date: 2007
  - Malcolm Smith
      ascent: second
      date:
  - Alan Cassidy
      ascent: third
      date: 

Overshadow
  grade: 9a+
  year: 2007
  ascents
    - Steve McClure
        ascent: first
        year: 2007
    - Adam Ondra
        ascent: second
        year: 2011

North Star
  grade: 9a
  year: 2008
  ascents:
    - Steve McClure, 20 May 2008
    - Adam Ondra, 2011

Stevolution
  grade: 9a
  year: 2008 or 2009
  ascents:
    - Steve McClure
        ascent: first
        date: 2009
    - Ryan Pasquill
        ascent: second
        date:

Blood Diamond
  grade: 8c+
  year: 2010
  ascents:
    - Malcolm Smith
        ascent: first
        date: June 2010

Hunger
  grade: 9a
  year: 2010
  - Malcolm Smith
      ascent: first
      date: 7 July 2010
  - Will Bosi
      ascent: second
      date: April 2008

Meltdown
  grade: 8c+/9a
  year: 2012
  ascents:
    - James McHaffie
        ascent: first
        date: Jul 2012 
    - Ignacio Mulero
        ascent: second

King of Theives
  grade: 8c+
  year: 2014
  ascents:
    - Jordan Buys
        ascent: 15 Sep 2014
    - Luke Dawson
        ascent: 12 Sep 2020

Brian
  grade: 8c+
  year:
  ascents:
  - Ken Palmer
  - Pete Dawson, 2 July 2017
  - Luke Dawson, 29 Oct 2018

Sabotage 2016
  grade: 8c+
  year: 2016
  ascents:
  - Neil Gresham
      ascent: first
      date: Oct 2016
  - Jon Freeman
      ascent: second
      date: 22 Sep 2020


Fixation
  grade: 8c+
  year: 2020
  ascents:
  - Steve McClure
      ascent: first
      date: September 2020
